### ISSUE TITLE
Make encode_all a class method, or add a float_format parameter to the method

### ISSUE THREAD

**Issue by mgoeminne** [ghilesmeddour/gorilla-time-series-compression#4]
Currently, `encode_all` is a static method of the `ValuesEncoder` class. Its usage can be misleading when a float format different from f64 is used:

``
content = gc.ValuesEncoder(float_format='f16').encode_all(sequence)
content['float_format']
``

The result is 'f64', since the method does not take into account the parameters of the instance of `ValuesEncoder` used to invoke the method.

I would suggest to make `encode_all` a class method, and/or add a `float_format` parameter to the static method to avoid this potential trouble.

**Comment by ghilesmeddour** [comment]
Hi @mgoeminne,

You are totally right. [I just added `float_format` parameter](https://github.com/ghilesmeddour/gorilla-time-series-compression/commit/bf04ceb8487228df0b4fd74969f9aa3b416fa87e), and pushed a new release [v0.2.1](https://pypi.org/project/gorillacompression/#history).

**Comment by mgoeminne** [comment]
Thanks a lot for your prompt reaction, @ghilesmeddour !
